# Generated by Django 5.1.6 on 2025-03-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('location', models.TextField()),
                ('installation_date', models.DateField()),
                ('panchayat_under', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('expenditure_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('dob', models.DateField()),
                ('educational_qualification', models.TextField()),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=15)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.TextField()),
                ('status', models.TextField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WelfareScheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentMonitor',
            fields=[
                ('monitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('citizen_id', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.citizen')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='household_id',
            field=models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.household'),
        ),
        migrations.CreateModel(
            name='CensusData',
            fields=[
                ('census_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.TextField()),
                ('event_date', models.DateField()),
                ('citizen_id', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.citizen')),
                ('household_id', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.household')),
            ],
        ),
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_type', models.TextField()),
                ('citizen_id', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='PanchayatEmployee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('citizen_id', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.TextField()),
                ('last_paid', models.DateField()),
                ('citizen_id', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('citizen_id', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.citizen')),
                ('scheme_id', models.ForeignKey(db_column='scheme_id', on_delete=django.db.models.deletion.CASCADE, to='panchayat.welfarescheme')),
            ],
        ),
    ]
