# Generated by Django 5.1.6 on 2025-03-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.RemoveField(
            model_name='censusdata',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='censusdata',
            name='household_id',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='household_id',
        ),
        migrations.RemoveField(
            model_name='panchayatemployee',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='landrecord',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='governmentmonitor',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='schemeenrollment',
            name='citizen_id',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.RemoveField(
            model_name='schemeenrollment',
            name='scheme_id',
        ),
        migrations.DeleteModel(
            name='CensusData',
        ),
        migrations.DeleteModel(
            name='Household',
        ),
        migrations.DeleteModel(
            name='PanchayatEmployee',
        ),
        migrations.DeleteModel(
            name='LandRecord',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.DeleteModel(
            name='GovernmentMonitor',
        ),
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='SchemeEnrollment',
        ),
        migrations.DeleteModel(
            name='WelfareScheme',
        ),
    ]
